# Generated by Django 5.2.8 on 2025-11-13 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OPEN', 'Open'), ('CLICK', 'Click'), ('REPORT', 'Report')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('campaign_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='campaigns.campaignrecipient')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type'], name='campaigns_e_event_t_4aacb8_idx'), models.Index(fields=['created_at'], name='campaigns_e_created_7e885c_idx')],
            },
        ),
    ]
