# Generated by Django 5.2.8 on 2025-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Planned start date/time for this campaign.', null=True),
        ),
    ]
