# Generated by Django 5.2.8 on 2025-11-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='scenario',
            field=models.CharField(choices=[('IT_ALERT', 'IT Security Alert'), ('PASSWORD_RESET', 'Password Reset'), ('PAYROLL', 'Payroll / Bank Details'), ('DELIVERY', 'Delivery Failure'), ('HR_POLICY', 'HR Policy Update')], default='IT_ALERT', help_text='Which built-in phishing scenario layout to use.', max_length=30),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Optional extra text. Placeholders like {{ first_name }} are allowed.'),
        ),
    ]
