# Generated by Django 5.2.8 on 2025-11-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='When emails were actually sent.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, help_text='Custom HTML email content. Use placeholders like {{ first_name }}, {{ click_url }}, {{ report_url }}. Only used when template_type is CUSTOM.'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sender_email',
            field=models.EmailField(blank=True, help_text="Sender email address (e.g., 'security@company.com'). If empty, uses system default.", max_length=254),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='sender_name',
            field=models.CharField(blank=True, help_text="Sender display name (e.g., 'IT Security Team')", max_length=200),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('SCENARIO', 'Pre-built Scenario'), ('CUSTOM', 'Custom HTML Email')], default='SCENARIO', help_text='Choose between pre-built scenario or custom HTML email.', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='scenario',
            field=models.CharField(blank=True, choices=[('IT_ALERT', 'IT Security Alert'), ('PASSWORD_RESET', 'Password Reset'), ('PAYROLL', 'Payroll / Bank Details'), ('DELIVERY', 'Delivery Failure'), ('HR_POLICY', 'HR Policy Update')], default='IT_ALERT', help_text='Which built-in phishing scenario layout to use (only for scenario type).', max_length=30),
        ),
    ]
