# Generated by Django 5.2.10 on 2026-01-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_add_email_composer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='scenario',
            field=models.CharField(blank=True, choices=[('IT_ALERT', 'IT Security Alert'), ('PASSWORD_RESET', 'Password Reset'), ('PAYROLL', 'Payroll / Bank Details'), ('DELIVERY', 'Delivery Failure'), ('HR_POLICY', 'HR Policy Update'), ('GENERAL', 'General internal email')], default='IT_ALERT', help_text="Which built-in phishing scenario layout to use (only for scenario type). Use 'General internal email' for normal HR / IT / company announcements that are not meant to look like phishing.", max_length=30),
        ),
    ]
